In [1]:
from pipeline import *

In [2]:
model_name = 'FLOW-3'
model_path = 'models/FLOW-3.h5'

df = []

data_path = '/workspaces/MultiFlow/data/debug'
for patient in tqdm(['UOISPAMIT1']):#,'NCHPHIREB1'][:]):
    p = Flow_Pipeline(patient, data_path, model_path, results_path)


  0%|          | 0/1 [00:00<?, ?it/s]

complex magnitude siemens
complex magnitude siemens
complex magnitude siemens
complex magnitude siemens
complex magnitude siemens
complex magnitude siemens


2026-03-17 14:38:22.970558: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2026-03-17 14:38:22.970586: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2026-03-17 14:38:22.970708: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model Loaded!
['l', 'pa', 'flow', 'v100']
0 ['l', 'pa', 'flow', 'v100'] tf.Tensor([[1. 0. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)
1/1 [==============================] - 1s 1s/step
['l', 'pa', 'flow', 'v100']
0 ['l', 'pa', 'flow', 'v100'] tf.Tensor([[1. 0. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)
1/1 [==============================] - 1s 792ms/step
['ao', 'flow', 'v200']
ao ['ao', 'flow', 'v200'] tf.Tensor([[0. 0. 0. 1. 0. 0.]], shape=(1, 6), dtype=float32)
1/1 [==============================] - 1s 810ms/step
['ivc', 'flow', 'v100']
ivc ['ivc', 'flow', 'v100'] tf.Tensor([[0. 0. 0. 0. 0. 1.]], shape=(1, 6), dtype=float32)
1/1 [==============================] - 1s 798ms/step
['svc', 'flow', 'v100']
svc ['svc', 'flow', 'v100'] tf.Tensor([[0. 0. 0. 0. 1. 0.]], shape=(1, 6), dtype=float32)
1/1 [==============================] - 1s 793ms/step
['svc', 'flow', 'v100']
svc ['svc', 'flow', 'v100'] tf.Tensor([[0. 0. 0. 0. 1. 0.]], shape=(1, 6), dtype=float32)
1/1 [==========================

100%|██████████| 1/1 [00:28<00:00, 28.43s/it]
